config/routes.rb
Rails.application.routes.draw do

  resources :tasks, only: :create

  root 'welcome#index'

  get "/home" => 'welcome#index'

end

app/models/my_job.rb
class MyJob

  @queue = :jobs_queue

  # to check redis:
  # run `redis-cli` and then type in 'PING'. if you get 'PONG' as a response then you're good.
  # if redis isn't running, run  `launchctl load /usr/local/opt/redis/homebrew.mxcl.redis.plist`
  # FYI, to check the history of anything you'ved ran in console before run `history | egrep -i YOURTERMHERE`

  # change this to write a file to a folder called "downloads" (you'll need to created this.)
  # use Time.now.to_i to name the file.
  # the phrase "hello, world" should be the contents of each file.
  # File.open("fubar.txt", "w+") { |f| f << "hi there!" }

  def self.perform
    file = "downloads/#{Time.now.to_i}.txt"
    sleep 1
    puts "look at me!: #{file}"

    File.open(file, "w+") { |f| f << "hello, world" }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # The 7 "standard" RESTful actions
  # index (show a collection of something)
  # show (show 1 of something)
  # new (the form to create something new)
  # create (the endpoint to process the form for something new)
  # edit (the form to edit something you've already created)
  # update (the endpoint to process the form for an update)
  # destroy (delete something)

  def create
    Resque.enqueue(MyJob)
    flash[:notice] = "Your job has been created."
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mission1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>


<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<br>

<%= link_to("Create Job", tasks_path, :method => :post) %>